import json

def create_layout_prompt(parsed_blueprint: dict) -> str:
    blueprint_str = json.dumps(
        parsed_blueprint,
        indent=2,
    )

    prompt = f"""You are an expert document intelligence engine specializing in legal and professional document architecture.

Your task is to analyze a structured document blueprint and organize all blocks into document groups.

The output will be used as the permanent navigation and generation configuration for a document generation system.

STRICT GROUPING RULES:

1. Group body blocks by shared legal or topical purpose — never by proximity alone.
2. A heading block MUST always be grouped with its following content blocks.
3. Empty blocks (content: "") are whitespace spacers and must belong to the nearest logical group.
4. A table block must either form its own group or belong to its immediately preceding content group.
5. No block may appear in more than one group.
6. Every block_id must be assigned exactly once.
7. Group names must be lowercase snake_case.
8. Preserve section_id exactly as provided.
9. Preserve metadata exactly as provided.
10. Return ONLY valid JSON.
11. No markdown.
12. No explanations.
13. No backticks.

SEMANTIC GROUP RULES:

14. Create semantic_groups only from body_blocks.
15. semantic_groups represent content that will later be generated by an LLM.
16. Every semantic group must have a unique execution_order.
17. execution_order starts at 1.
18. execution_order increments sequentially.
19. Prefix semantic group names with a zero-padded execution order.
20. Example:

    * 01_case_header
    * 02_claimant_details
    * 03_accident_description

HEADER AND FOOTER RULES:

21. Create exactly one header_group per section.
22. Create exactly one footer_group per section.
23. header_group must contain all header_blocks belonging to that section.
24. footer_group must contain all footer_blocks belonging to that section.
25. header_blocks MUST NOT appear in semantic_groups.
26. footer_blocks MUST NOT appear in semantic_groups.
27. header_group is used for future editing and document assembly.
28. footer_group is used for future editing and document assembly.
29. header_group and footer_group are NOT part of semantic group generation.

DESCRIPTION RULES:

30. Every semantic group description must clearly explain:

    * what the group contains
    * whether the content is fixed or variable
    * what information is expected in the group

31. Header and footer descriptions should explain their purpose in the document.

INPUT BLUEPRINT:

{blueprint_str}

REQUIRED OUTPUT FORMAT:

{{
"sections": [
{{
"section_id": "section_1",

  "metadata": {{
    "...": "preserve exactly as input"
  }},

  "header_group": {{
    "name": "section_header",
    "description": "Header content for this section.",
    "blocks": [
      "header_0"
    ]
  }},

  "semantic_groups": [
    {{
      "execution_order": 1,
      "name": "01_group_name",
      "description": "Clear description.",
      "blocks": [
        "block_1",
        "block_2"
      ]
    }}
  ],

  "footer_group": {{
    "name": "section_footer",
    "description": "Footer content for this section.",
    "blocks": [
      "footer_0"
    ]
  }}
}}
]
}}
"""

    return prompt
